---

- name: install dependency packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - nginx
    - gzip

- name: add mailhog proxy config
  ansible.builtin.template:
    src: mailhog.conf.j2
    dest: /etc/nginx/sites-available/mailhog.conf
    owner: root
    group: root
    mode: 0644

- name: create a symbolic link for mailhog.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mailhog.conf
    dest: /etc/nginx/sites-enabled/mailhog.conf
    owner: root
    group: root
    state: link


- name: add adminer proxy config
  ansible.builtin.template:
    src: adminer.conf.j2
    dest: /etc/nginx/sites-available/adminer.conf
    owner: root
    group: root
    mode: 0644

- name: create a symbolic link for adminer.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/adminer.conf
    dest: /etc/nginx/sites-enabled/adminer.conf
    owner: root
    group: root
    state: link

- name: add odoo proxy config
  ansible.builtin.template:
    src: odoo.conf.j2
    dest: /etc/nginx/sites-available/odoo.conf
    owner: root
    group: root
    mode: 0644

- name: create a symbolic link for odoo.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/odoo.conf
    dest: /etc/nginx/sites-enabled/odoo.conf
    owner: root
    group: root
    state: link

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

...
