---

- hosts: all
  become: true
  become_method: sudo

  vars:
    wkhtmltopdf_install_google_fonts: False
    postgresql_listen: "0.0.0.0"
    postgresql_databases:
    - name: odoo_preseed
      encoding: UTF-8
      extensions: []
      state: present
      schemas:
      - name: odoo_preseed
        state: present
    postgresql_users:
    - name: odoo
      password: odoo_secret
      state: present
      role_attr_flags: CREATEDB,NOSUPERUSER
      privileges:
      - database: odoo_preseed
        privs: "All"
        state: present
      hosts:
      - cidr: localhost
        database: odoo_preseed
        state: present
      - cidr: 0.0.0.0/0
        database: odoo_preseed
        state: present

  pre_tasks:
  - name: Include custom_vars.yml
    include_vars:
      file: custom_vars.yml

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.mailpit
  - pgadmin
  - andrelohmann.nodesource
  - andrelohmann.wkhtmltopdf
  - andrelohmann.postgresql
  - odoo_dependencies
  - odoo_installer
  - proxy

  tasks:
  - name: install useful packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - net-tools
      - telnet


...
