---

- hosts: all
  become: true
  become_method: sudo

  vars:
    wkhtmltopdf_install_google_fonts: False
    postgresql_listen: "0.0.0.0"
    postgresql_databases:
    - name: odoo
      encoding: UTF-8
      state: present
      schemas:
      - name: odoo
        state: present
    postgresql_users:
    - name: odoo
      password: odoo_secret
      state: present
      privileges:
      - database: odoo
        privs: "All"
        state: present
      hosts:
      - cidr: 0.0.0.0/0
        database: odoo
        state: present

  #pre_tasks:
  #- name: Include custom_vars.yml
  #  include_vars:
  #    file: custom_vars.yml

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.wkhtmltopdf
  - andrelohmann.postgresql
  - andrelohmann.nodesource

  tasks:

  - name: install dependency packages
    apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - git
      - python3-dev
      - libxml2-dev
      - libxslt1-dev
      - libldap2-dev
      - libsasl2-dev

  - name: install required python packages
    pip:
      name: "{{ required_python_packages }}"
      extra_args: --upgrade
      executable: pip3
    vars:
      required_python_packages:
      - setuptools
      - wheel


  - name: install required python packages
    pip:
      name: "{{ required_python_packages }}"
      extra_args: --upgrade
      executable: pip3
    vars:
      required_python_packages:
      - setuptools
      - wheel

  - name: install required npm packages
    npm:
      name: "{{ required_npm_packages }}"
      global: yes
    vars:
      required_npm_packages:
      - rtlcss

...
