---

- hosts: all
  become: true
  become_method: sudo

  vars:
    wkhtmltopdf_install_google_fonts: False
    postgresql_listen: "0.0.0.0"
    postgresql_databases:
    - name: odoo_preseed
      encoding: UTF-8
      extensions: []
      state: present
      schemas:
      - name: odoo_preseed
        state: present
    postgresql_users:
    - name: odoo
      password: odoo_secret
      state: present
      role_attr_flags: CREATEDB,NOSUPERUSER
      privileges:
      - database: odoo_preseed
        privs: "All"
        state: present
      hosts:
      - cidr: localhost
        database: odoo_preseed
        state: present
      - cidr: 0.0.0.0/0
        database: odoo_preseed
        state: present
    mailpit_domain: mail.odoo.lokal
    pgadmin_domain: pgadmin.odoo.lokal
    pgadmin_email: admin@pgadmin.odoo.lokal
    pgadmin_password: admin
    odoo_domain: odoo.lokal
    odoo_additional_domains: "www.odoo.lokal shop.odoo.lokal"
    odoo_admin_password: P@ssw0rd!
    odoo_preseed: false

  pre_tasks:
  - name: check for file custom_vars.yml
    stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.mailpit
  - pgadmin
  - andrelohmann.nodesource
  - andrelohmann.wkhtmltopdf
  - andrelohmann.postgresql
  - odoo_dependencies
  - odoo_installer
  - proxy

  tasks:
  - name: install useful packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - net-tools
      - telnet

...
