---

- hosts: all
  become: true
  become_method: sudo

  vars:
    mailhog_smtp_port: 25
    wkhtmltopdf_install_google_fonts: False
    postgresql_listen: "0.0.0.0"
    postgresql_databases:
    - name: odoo
      encoding: UTF-8
      extensions: []
      state: present
      schemas:
      - name: odoo
        state: present
    postgresql_users:
    - name: odoo
      password: odoo_secret
      state: present
      privileges:
      - database: odoo
        privs: "All"
        state: present
      hosts:
      - cidr: localhost
        database: odoo
        state: present
      - cidr: 0.0.0.0/0
        database: odoo
        state: present
    apache_php_version: 8.2
    apache_php_ini_settings:
    - key: post_max_size
      value: 512M
    - key: upload_max_filesize
      value: 512M
    - key: max_execution_time
      value: 600
    - key: max_input_time
      value: 600
    sury_php_packages:
    - php8.2-gd
    - php8.2-mysql
    - php8.2-curl
    - php8.2-mcrypt
    - php8.2-tidy
    - php8.2-zip
    - php-imagick
    - php-geoip
    - geoip-bin
    apache_php_additional_modules:
    - name: rewrite
      state: present
    apache_php_remove_default_vhost: true

  pre_tasks:
  - name: Include custom_vars.yml
    include_vars:
      file: custom_vars.yml

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.sury_php
  - andrelohmann.apache_php
  - adminer
  #- pgadmin
  - andrelohmann.mailhog
  - andrelohmann.wkhtmltopdf
  - andrelohmann.postgresql
  - andrelohmann.nodesource
  - odoo_dependencies
  - odoo_installer
  - proxy


...
