---
roles:
- andrelohmann.root_colored_prompt
- andrelohmann.mailpit
- andrelohmann.wkhtmltopdf
- andrelohmann.postgresql
- andrelohmann.nodesource
- andrelohmann.maxmind
- andrelohmann.odoo

collections:
- community.postgresql
- community.general
...
