---

- name: create group odoo
  ansible.builtin.group:
    name: odoo
    state: present

- name: create user odoo
  ansible.builtin.user:
    name: odoo
    group: odoo
    shell: /bin/bash
    state: present
    system: yes
    home: /opt/odoo

- name: add systemd unit file
  ansible.builtin.template:
    src: odoo.conf.j2
    dest: /etc/odoo17.conf
    owner: root
    group: root
    mode: 0644

- name: add systemd unit file
  ansible.builtin.copy:
    src: odoo.conf.template
    dest: /etc/odoo17.conf.template
    owner: root
    group: root
    mode: 0644

- name: clone odoo
  ansible.builtin.git:
    repo: https://github.com/odoo/odoo.git
    dest: /opt/odoo/odoo17
    depth: 1
    version: "17.0"
  become: yes
  become_user: odoo

## SEEMS TO HAVE CHANGED IN ODOO15
# max_upload_size is sadly a fixed value in addons/web/static/src/js/fields/basic_fields.js
# replace "        this.max_upload_size = 25 * 1024 * 1024; // 25Mo"
# with "        this.max_upload_size = 1024 * 1024 * 1024; // 1024Mo"
#- name: replace max_upload_size
#  lineinfile:
#    path: "/opt/odoo/odoo15/addons/web/static/src/legacy/js/fields/basic_fields.js"
#    regexp: "^        this.max_upload_size = 25 * 1024 * 1024; // 25Mo"
#    line: "        this.max_upload_size = 1024 * 1024 * 1024; // 1024Mo"
# maybe override functionality is a better way around it
# https://stackoverflow.com/questions/58395492/override-javascript-function-in-odoo#:~:text=This%20means%20you%20cannot%20override,odoo.
# https://www.odoo.com/fr_FR/forum/aide-1/question/odoo-10-how-to-override-javascript-function-137833
# https://supportuae.wordpress.com/2017/08/06/how-to-override-form-widgets-odoo-javascript/

# Seems to be breaking in odoo16 - dependencies are installed in odoo_dependencies role
#- name: install pip3 requirements
#  ansible.builtin.pip:
#    requirements: /opt/odoo/odoo16/requirements.txt
#    executable: pip3

- name: add systemd unit file
  ansible.builtin.copy:
    src: odoo.service
    dest: /etc/systemd/system/odoo.service
    owner: root
    group: root
    mode: 0644

- name: Create /var/log/odoo directory
  ansible.builtin.file:
    path: /var/log/odoo
    state: directory
    owner: odoo
    group: odoo
    mode: 0755

- name: Create /var/log/odoo/odoo.log directory
  ansible.builtin.file:
    path: /var/log/odoo/odoo.log
    state: touch
    owner: odoo
    group: odoo
    mode: 0755

# https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781785884887/1/ch01lvl1sec9/initializing-a-new-odoo-database
# https://www.odoo.com/documentation/13.0/reference/cmdline.html#database
- name: initialize database
  ansible.builtin.shell: /usr/bin/python3 /opt/odoo/odoo17/odoo-bin --database odoo_preseed --db_user odoo --db_password odoo_secret --db_host localhost --db_port 5432 --init base --stop-after-init
  args:
    executable: /bin/bash
  become: yes
  become_user: odoo
  when: odoo_preseed

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: systemctl enable odoo
  ansible.builtin.systemd:
    name: odoo
    enabled: yes

- name: systemctl start odoo
  ansible.builtin.systemd:
    state: started
    name: odoo

...
