---

- name: create group odoo
  group:
    name: odoo
    state: present

- name: create user odoo
  user:
    name: odoo
    group: odoo
    shell: /bin/bash
    state: present
    system: yes
    home: /opt/odoo

- name: add systemd unit file
  template:
    src: odoo.conf.j2
    dest: /etc/odoo13.conf
    owner: root
    group: root
    mode: 0644

- name: add systemd unit file
  copy:
    src: odoo.conf.template
    dest: /etc/odoo13.conf.template
    owner: root
    group: root
    mode: 0644

- name: clone odoo
  git:
    repo: https://github.com/odoo/odoo.git
    dest: /opt/odoo/odoo13
    depth: 1
    version: "13.0"
  become: yes
  become_user: odoo

- name: install pip3 requirements
  pip:
    requirements: /opt/odoo/odoo13/requirements.txt
    executable: pip3

- name: add systemd unit file
  copy:
    src: odoo.service
    dest: /etc/systemd/system/odoo.service
    owner: root
    group: root
    mode: 0644

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: systemctl enable odoo
  systemd:
    name: odoo
    enabled: yes

- name: systemctl start odoo
  systemd:
    state: started
    name: odoo

...
